### ISSUE TITLE
Drifiting bug

### ISSUE THREAD

**Issue by fyradur** [gnol-on-the-beat/Mario-kart-test#1]
Drifting only gets the expected behavior when turning right, but not left.

**Comment by fyradur** [comment]
More specifically, when holding down the accelerator and drifting buttons the left key does not affect the car at all whereas the right key works correctly.

**Comment by fyradur** [comment]
This could be because the steering angle perhaps determines direction depending on positive or negative. In the code, steering angles are compared only considering if they are larger, and not if they have a larger magnitude.

**Comment by gnol-on-the-beat** [comment]
I can't replicate the bug. Are you monitoring a value to check for expected behaviour?

**Comment by fyradur** [comment]
Can't be replicated + works on my computer with a different keyboard.  The bug can safely be assumed to be a client-side error with my laptop keyboard.
